apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-acbw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-acbw
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-acbw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-acbw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-acbw
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-bjqa-tenant/private-devfile/private-quarkus-devfile-sample-acbw@sha256:e7e5085e7af84798a4ff93f7e0ae623a738a62cccf50d8910249dc7271c832ae
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
